version: '3.4'

networks:
  dev:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 5252:5252
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=bookdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: NhonVTT-Template-redis
    ports:
      - 6378:6378
    restart: always

  wire_mock:
    image: rodolpheche/wiremock
    command: --local-response-templating
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
    ports:
      - 4656:8080

volumes:
  app_data:
